### ISSUE TITLE
Links to videos, logs and jobs are incorrect

### ISSUE THREAD

**Issue by rycornell** [saucelabs/vso-sauce-ondemand-plugin#4]
On the Sauce Labs tab in TFS, the links to the test video, logs, and job name are all broken.  The links to the video and logs in particular seem to be missing the 'assets' subdomain in the url.

**Comment by yfangsl** [comment]
@rycornell Hi, can you please contact support@saucelabs.com with this issue so it can be properly tracked and assigned internally? Thank you.
